# Generated by Django 5.0.2 on 2024-03-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0009_alter_alertrecipient_recipient_type"),
        ("issue_events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="issues",
            field=models.ManyToManyField(to="issue_events.issue"),
        ),
        migrations.AddField(
            model_name="notification",
            name="issues",
            field=models.ManyToManyField(to="issue_events.issue"),
        ),
    ]
