# Generated by Django 5.0.2 on 2024-03-12 13:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_squashed_0003_auto_20210219_1951"),
        ("issues", "0013_alter_comment_options_alter_issue_unique_together_and_more"),
        ("issue_events", "0001_initial"),
    ]

    operations = []
