# Generated by Django 5.0.3 on 2024-03-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20240312_1344'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
