# Generated by Django 5.0.3 on 2024-03-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_delete_event'),
        ('issues', '0013_alter_comment_options_alter_issue_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
        migrations.RemoveField(
            model_name='issuehash',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issuehash',
            name='project',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='IssueHash',
        ),
    ]
