# Generated by Django 5.0.6 on 2024-07-04 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("performance", "0001_squashed_0012_alter_span_op"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Span",
        ),
        migrations.DeleteModel(
            name="TransactionEvent",
        ),
        migrations.DeleteModel(
            name="TransactionGroup",
        ),
    ]
