# Generated by Django 5.0.7 on 2024-07-27 18:49

from django.db import migrations

from allauth.mfa.adapter import get_adapter


def migrate_mfa(apps, schema_editor):
    UserKey = apps.get_model("django_rest_mfa", "UserKey")
    Authenticator = apps.get_model("mfa", "Authenticator")

    adapter = get_adapter()
    authenticators = []
    for totp in UserKey.objects.filter(key_type="TOTP").iterator():
        recovery_codes = set()
        for backup_code in UserKey.objects.filter(
            key_type="Backup Codes", user_id=totp.user_id
        ):
            recovery_codes.update(backup_code.properties["codes"])
        secret = totp.properties["secret_key"]
        authenticators.append(
            Authenticator(
                user_id=totp.user_id,
                type="totp",
                data={"secret": adapter.encrypt(secret)},
            )
        )
        if recovery_codes:
            authenticators.append(
                Authenticator(
                    user_id=totp.user_id,
                    type="recovery_codes",
                    data={
                        "migrated_codes": [adapter.encrypt(c) for c in recovery_codes],
                    },
                )
            )
    Authenticator.objects.bulk_create(authenticators)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_email"),
    ]

    operations = [migrations.RunPython(migrate_mfa, migrations.RunPython.noop)]
